version: '3.7'
services:
    backend:
        image: 'node'
        container_name: nodejs-express-example-deploy
        working_dir: /app
        volumes:
            - './backend:/app'
        ports:
            - '3333:3000'
        environment:
            - PORT=3000
        command: /bin/bash -c "yarn && node index.js"
