version: '3.7'
services:
    backend:
        image: 'node'
        container_name: simplytodo-backend
        working_dir: /app
        volumes:
            - './backend:/app'
        ports:
            - '3333:3000'
        environment:
            - PORT=3000
        command: /bin/bash -c "yarn && yarn build && yarn typeorm migration:run && NODE_ENV=production node dist/server.js"
